spring.application.name=demo-e15
# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/demoe15
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true